### ISSUE TITLE
planned support for ClusterIssuer ?

### ISSUE THREAD

**Issue by steliandoruzaharia** [cloudflare/origin-ca-issuer#49] opened 2021-12-07 11:19 UTC
Hello .

Is there any support or planned support for ClusterIssuer  kind ?

We're looking to send requests from different namespaces without deploying the  OriginIssuer and key in each namespace and wonder if this will be supported . 

Thanks .

**Comment by terinjokes** [comment] 2021-12-07 17:40
Duplicate of #24. Planned, but not yet implemented.

**Closed as completed by terinjokes** 2021-12-07 17:40 UTC
