### ISSUE TITLE
Origin CA Issuer rejects rather than ignores CertificateRequests with a missing spec.issuerRef.group

### ISSUE THREAD

**Issue by KingJ** [cloudflare/origin-ca-issuer#149] opened 2024-11-01 11:41 UTC
We recently upgraded Origin CA Issuer from v0.8.0 to v0.9.0 in our lab environment. Following this, a number of Cert Manager `Certificate` objects have failed to issue. The `CertificateRequest` for these certificates contains the following status condition;

```
    - lastTransitionTime: '2024-11-01T09:23:52Z'
      message: 'Unknown issuer kind: Issuer'
      reason: Failed
      status: 'False'
      type: Ready
```

The `Certificate` and the associated `Issuer` are rather bare-bones. The following manifest was used to replicate the issue;

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  dnsNames:
    - capi-operator-webhook-service.capi-operator-system.svc
    - capi-operator-webhook-service.capi-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: test-selfsigned-issuer
  secretName: test-cert
```

If the `Certificate`'s `spec.issuerRef.group` is subsequently set to `cert-manager.io`, then the certificate is issued successfully. Setting the group is optional when using one of Cert Manager's own internal issuers - it only needs to be set for external issues like the Origin CA Issuer.

While troubleshooting this issue with Cert Manager's developers, we discovered that it was not Cert Manager's own internal self-signed issuer that was returning this error - but the Origin CA Issuer. From the Origin CA Issuer logs;

```
{"level":"error","namespace":"default","certificaterequest":"test-cert-1","error":"unknown issuer kind: Issuer","logger":"origin-issuer/controllers/CertificateRequest","namespace":"default","name":"test-cert-1","caller":"/go/src/app/pkgs/controllers/certificaterequest.go:175","time":1730458599171,"message":"certificate request references unknown issuer kind"}
{"level":"error","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"test-cert-1","namespace":"default"},"namespace":"default","name":"test-cert-1","reconcileID":"4ddcbbb2-c258-4202-ac40-8e45d5454bbb","error":"unknown issuer kind: Issuer","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329","time":1730458599191,"message":"Reconciler error"}
```

As issuers are expected to process `CertificateRequests` in parallel, Cert Manager will only accept the first response back from an issuer. Issuers are expected to ignore `CertificateRequests` that do not relate to them - however, the Origin CA Issuer handles the `CertificateRequest` generated from the `Certificate` above and rejects it - therefore if Cert Manager's own internal self-signed issuer responds slower than the Origin CA Issuer, the Certificate will not be issued successfully.

Setting the `Certificate`'s `spec.issuerRef.group` is subsequently set to `cert-manager.io` bypasses this issue, as the Origin CA Issuer correctly ignores the `CertificateRequest` - it is only when `spec.issuerRef.group` is unset (which is valid) that the Origin CA Issuer incorrectly handles the `CertificateRequest` and thus returns an error.

Origin CA Issuer should be fixed to perform a more explicit check on `spec.issuerRef` - and only handle requests where the `group` is explicitly set to `cert-manager.k8s.cloudflare.com`.

**Comment by SgtCoDFish** [comment] 2024-11-01 12:02
👋  cert-manager maintainer here!

I think the line which causes the issue is https://github.com/cloudflare/origin-ca-issuer/blob/ec06da1e084fe7f564befaa464c30ded11c59463/pkgs/controllers/certificaterequest.go#L170

Our recommended logic [in issuer-lib](https://github.com/cert-manager/issuer-lib/blob/1df604ef01ce6b912b2abb12bd75acf57697ada9/controllers/certificaterequest_controller.go#L55-L58) is to ignore any CertificateRequests which don't match the group defined by the issuer.

It seems origin-ca-issuer is not doing that, and is checking for a matching kind.

There are two issues here:

1. Issuers must ignore CertificateRequests which are not marked for them and must not set an error on the CR in that case. This is what causes the race which @KingJ saw.

2. It would probably be preferable to require the group to match the defined group for this issuer always, although I recognise that this is likely to be a breaking change for users who are otherwise just setting `kind: OriginIssuer`.

Reasoning behind issue 2:

1. As things stand, if anyone else creates an issuer with the same name but a different group users will see race conditions with this issuer.

2. It also may negatively interact with other tools which follow the convention that an empty group is equivalent to `cert-manager.io`.

Issue 1 is definitely more important though - as things stand, v0.9.0 and v0.10.0 of origin-ca-issuer can break other unrelated certs in a cluster when installed and it's not obvious to users what happens!

**Comment by terinjokes** [comment] 2024-11-01 12:07
When the check earlier in the function was written it was assumed that all CRs had a group. Four years later when I added a new kind I added a default case to catch any unknown issuers in our group and rejects if not known.

I'll fix the group check to ensure we don't try to reconcile empty groups.

**Comment by terinjokes** [comment] 2024-11-01 23:42
Fixed in https://github.com/cloudflare/origin-ca-issuer/releases/tag/v0.11.0.

**Closed as completed by terinjokes** 2024-11-01 23:42 UTC

**Comment by KingJ** [comment] 2024-11-04 14:41
Thank you very much for the fast turnaround on this @terinjokes , I can confirm that after upgrading to v0.11.0 we no longer see this issue. Thank you too to @SgtCoDFish for all of the help in diagnosing this in the first place as well as putting the suggested fix on here.

**Comment by terinjokes** [comment] 2024-11-04 15:02
Glad to hear 0.11.0 is working well. Sorry for causing the issue in the first place.

I'm working on a branch that tries out the aforementioned issuer-lib, with the hope I can reduce the possibility for errors with the CertificateRequest lifecycles. There have been a few misunderstandings based on the early docs from when I originally wrote this issuer.
