### ISSUE TITLE
Helm Chart general improvements

### ISSUE THREAD

**Issue by sidineyc** [cloudflare/origin-ca-issuer#63] opened 2022-05-25 10:31 UTC
The issues are: 

- The chart doesn't include the CRDs definitions, this can be done by adding the definitions under `crds` directory. More info can be found [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) 
If one doesn't want to include the CRDs automatically is just about setting `--skip-crds` flag
- As mentioned on #45 , the chart just assumes the namespace and also the service account name used by cert-manager, that is not always the case.

**Comment by terinjokes** [comment] 2022-05-25 23:10
Closing as duplicate of #45,

**Closed as not planned by terinjokes** 2022-05-25 23:10 UTC
