### ISSUE TITLE
Unable to refresh certificate

### ISSUE THREAD

**Issue by tnimni** [cloudflare/origin-ca-issuer#107] opened 2024-01-15 12:28 UTC
Hi,
Using version 0.6.0 of this issuer
We start getting this error today
```status:
  conditions:
  - lastTransitionTime: "2024-01-15T12:22:58Z"
    message: Certificate request has been approved by cert-manager.io
    reason: cert-manager.io
    status: "True"
    type: Approved
  - lastTransitionTime: "2024-01-15T12:23:00Z"
    message: 'Failed to sign certificate request: unable to sign request: Cloudflare
      API Error code=10000 message=Authentication error'
    reason: Failed
    status: "False"
    type: Ready
```
    
   We double checked and our api key is valid and has the same value that shows in cloudflare UI
   We also tried this api call with postman 
```curl --location 'https://api.cloudflare.com/client/v4/user/tokens/verify' \
--header 'Authorization: Bearer REDUCATED' \
--header 'Content-Type: application/json' \`
and we got the following
status code: 200 `{
    "result": {
        "id": "REDUCTED",
        "status": "active"
    },
    "success": true,
    "errors": [],
    "messages": [
        {
            "code": 10000,
            "message": "This API Token is valid and active",
            "type": null
        }
    ]
}
```
So it seems to be an issue with the controller
Please advise what we can do about it

**Comment by terinjokes** [comment] 2024-01-15 12:38
Duplicate of #105

**Closed as completed by terinjokes** 2024-01-15 12:38 UTC
