### ISSUE TITLE
Invalid value "OriginIssuer" 

### ISSUE THREAD

**Issue by JoeApo108** [cloudflare/origin-ca-issuer#71] opened 2022-10-31 19:46 UTC
With cert-manager in **version v1.10.0** cert-manager-controller throws the following error, certs are successfully issued though. 
The **issuerRef.kind** requirements have changed.

`E1031 19:23:01.329393       1 checks.go:95] cert-manager/controller/certificaterequests-issuer-selfsigned/handleSecretReference "msg"="failed to get issuer" "error"="invalid value \"OriginIssuer\" for issuerRef.kind. Must be empty, \"Issuer\" or \"ClusterIssuer\"" "resource_kind"="Secret" "resource_name"="server37-k9rtd" "resource_namespace"="default" "resource_version"="v1" `

**Comment by terinjokes** [comment] 2022-11-01 14:58
Do you have an example of what you're doing? As best I can tell the requirements have not changed.,

**Comment by rarecrumb** [comment] 2022-11-02 17:46
.

**Comment by terinjokes** [comment] 2022-11-02 18:04
That looks correct to me. AFAICT, I have nothing to do with this code path. Do you by chance have a SelfSigned Issuer configured in this cluster?

@JoshVanL Based on the error message here, this looks to be a regression caused by https://github.com/cert-manager/cert-manager/pull/5336. WDYT?

**Comment by rarecrumb** [comment] 2022-11-02 18:30
.

**Comment by terinjokes** [comment] 2022-11-02 19:20
> my certificates still don't seem to get verified

This is likely an unrelated issue. The OP reported that despite this issue the certificates issued just fine (which makes sense, the self-signed issuer is the one complaining here).

**Comment by JoeApo108** [comment] 2022-11-03 16:56
Is it what I said in my first post, currently there's no issue with the certificate issuance. All works as intended. The whole point is that it appeared in the latest **v1.10.0** version (definitely it didn't in **v1.9.1**) and might or might not have an effect on correct behavior in future releases. 

Maybe it's just enough to edit CRD objects to stay on track with the new requirements of the **cert-manager** plugin.

**Comment by terinjokes** [comment] 2022-11-03 17:39
As mentioned above, I believe this is a bug in cert-manager, where the selfsigned controller is looking resources it's not responsible for managing, then logging an error. I plan on opening a bug there with more information.

**Comment by SgtCoDFish** [comment] 2022-12-05 10:23
I think we already have a relevant bug open on cert-manager: https://github.com/cert-manager/cert-manager/issues/5601

This is a confusing log message which shouldn't be printed - but issuance shouldn't ever be affected by this as far as I understand! :grin:

**Comment by terinjokes** [comment] 2023-02-05 12:47
Closing because it was fixed upstream in 1.11.0. Thanks for the PR there @SgtCoDFish.

**Closed as completed by terinjokes** 2023-02-05 12:47 UTC
